language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer self-update
    - composer install
    - mysql -e 'create database mydb;'
    - php vendor/bin/phinx migrate
    - php vendor/bin/phinx migrate -c vendor/infuse/auth/phinx.yml

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls